In [61]:
import pandas as pd
import ast
import numpy as np

In [62]:
INPUT_FILE = "../data/processed/cleaned_movies.csv"
OUTPUT_FILE = "../data/processed/final_dataset.csv"

In [63]:
GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "History",
    "Horror",
    "Music",
    "Mystery",
    "Romance",
    "Science Fiction",
    "Thriller",
    "War",
    "Western"
]

In [64]:
movies = pd.read_csv(INPUT_FILE)

print("Dataset loaded.")
print("Shape:", movies.shape)

Dataset loaded.
Shape: (5363, 15)

In [65]:
movies.head()

,id,title,budget,revenue,runtime,popularity,vote_average,vote_count,original_language,genres,production_countries,spoken_languages,release_date,release_year,release_month
0,862,Toy Story,30000000.0,373554033.0,81.0,21.946943,7.7,5415.0,en,"['Animation', 'Comedy', 'Family']",['United States of America'],['English'],1995-10-30,1995.0,10.0
1,8844,Jumanji,65000000.0,262797249.0,104.0,17.015539,6.9,2413.0,en,"['Adventure', 'Fantasy', 'Family']",['United States of America'],"['English', 'Français']",1995-12-15,1995.0,12.0
2,31357,Waiting to Exhale,16000000.0,81452156.0,127.0,3.859495,6.1,34.0,en,"['Comedy', 'Drama', 'Romance']",['United States of America'],['English'],1995-12-22,1995.0,12.0
3,949,Heat,60000000.0,187436818.0,170.0,17.924927,7.7,1886.0,en,"['Action', 'Crime', 'Drama', 'Thriller']",['United States of America'],"['English', 'Español']",1995-12-15,1995.0,12.0
4,9091,Sudden Death,35000000.0,64350171.0,106.0,5.231580,5.5,174.0,en,"['Action', 'Adventure', 'Thriller']",['United States of America'],['English'],1995-12-22,1995.0,12.0

In [66]:
movies["genres"] = movies["genres"].apply(
    lambda x: ast.literal_eval(x)
    if isinstance(x, str)
    else []
)

movies["production_countries"] = movies[
    "production_countries"
].apply(
    lambda x: ast.literal_eval(x)
    if isinstance(x, str)
    else []
)

print("List columns converted.")

List columns converted.

In [67]:
print(movies["genres"].head())
print(movies["production_countries"].head())

0         [Animation, Comedy, Family]
1        [Adventure, Fantasy, Family]
2            [Comedy, Drama, Romance]
3    [Action, Crime, Drama, Thriller]
4       [Action, Adventure, Thriller]
Name: genres, dtype: object
0    [United States of America]
1    [United States of America]
2    [United States of America]
3    [United States of America]
4    [United States of America]
Name: production_countries, dtype: object

In [68]:
for genre in GENRES:
    column_name = "genre_" + genre.lower().replace(" ", "_")

    movies[column_name] = movies["genres"].apply(
        lambda genres: 1 if genre in genres else 0
    )

print("Genre features created.")

Genre features created.

In [69]:
genre_columns = [
    "genre_" + genre.lower().replace(" ", "_")
    for genre in GENRES
]

movies[genre_columns].head()

,genre_action,genre_adventure,genre_animation,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_war,genre_western
0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
3,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0
4,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [70]:
movies["main_country"] = movies[
    "production_countries"
].apply(
    lambda countries: countries[0]
    if len(countries) > 0
    else "Unknown"
)

print("Main country feature created.")

Main country feature created.

In [71]:
movies[
    [
        "title",
        "production_countries",
        "main_country"
    ]
].head()

               title        production_countries              main_country
0          Toy Story  [United States of America]  United States of America
1            Jumanji  [United States of America]  United States of America
2  Waiting to Exhale  [United States of America]  United States of America
3               Heat  [United States of America]  United States of America
4       Sudden Death  [United States of America]  United States of America

In [72]:
movies["log_budget"] = np.log1p(
    movies["budget"]
)

print("Log budget feature created.")

Log budget feature created.

In [73]:
movies["log_revenue"] = np.log1p(
    movies["revenue"]
)

print("Log revenue feature created.")

Log revenue feature created.

In [74]:
movies[
    [
        "budget",
        "log_budget",
        "revenue",
        "log_revenue"
    ]
].head()

       budget  log_budget      revenue  log_revenue
0  30000000.0   17.216708  373554033.0    19.738573
1  65000000.0   17.989898  262797249.0    19.386893
2  16000000.0   16.588099   81452156.0    18.215526
3  60000000.0   17.909855  187436818.0    19.048952
4  35000000.0   17.370859   64350171.0    17.979850

In [75]:
feature_columns = [
    "budget",
    "log_budget",
    "runtime",
    "release_year",
    "release_month",
    "original_language",
    "main_country"
]

genre_columns = [
    "genre_" + genre.lower().replace(" ", "_")
    for genre in GENRES
]

feature_columns.extend(genre_columns)

feature_columns.append("revenue")
feature_columns.append("log_revenue")

movies = movies[feature_columns]

print("Features selected.")

Features selected.

In [76]:
print("Final dataset shape:", movies.shape)

print("\nFinal columns:")
print(movies.columns.tolist())

Final dataset shape: (5363, 27)

Final columns:
['budget', 'log_budget', 'runtime', 'release_year', 'release_month', 'original_language', 'main_country', 'genre_action', 'genre_adventure', 'genre_animation', 'genre_comedy', 'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family', 'genre_fantasy', 'genre_history', 'genre_horror', 'genre_music', 'genre_mystery', 'genre_romance', 'genre_science_fiction', 'genre_thriller', 'genre_war', 'genre_western', 'revenue', 'log_revenue']

In [77]:
movies.head()

,budget,log_budget,runtime,release_year,release_month,original_language,main_country,genre_action,genre_adventure,genre_animation,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_war,genre_western,revenue,log_revenue
0,30000000.0,17.216708,81.0,1995.0,10.0,en,United States of America,0,0,1,...,0,0,0,0,0,0,0,0,373554033.0,19.738573
1,65000000.0,17.989898,104.0,1995.0,12.0,en,United States of America,0,1,0,...,0,0,0,0,0,0,0,0,262797249.0,19.386893
2,16000000.0,16.588099,127.0,1995.0,12.0,en,United States of America,0,0,0,...,0,0,0,1,0,0,0,0,81452156.0,18.215526
3,60000000.0,17.909855,170.0,1995.0,12.0,en,United States of America,1,0,0,...,0,0,0,0,0,1,0,0,187436818.0,19.048952
4,35000000.0,17.370859,106.0,1995.0,12.0,en,United States of America,1,1,0,...,0,0,0,0,0,1,0,0,64350171.0,17.979850

In [78]:
movies.isnull().sum()

budget                   0
log_budget               0
runtime                  0
release_year             0
release_month            0
original_language        0
main_country             0
genre_action             0
genre_adventure          0
genre_animation          0
genre_comedy             0
genre_crime              0
genre_documentary        0
genre_drama              0
genre_family             0
genre_fantasy            0
genre_history            0
genre_horror             0
genre_music              0
genre_mystery            0
genre_romance            0
genre_science_fiction    0
genre_thriller           0
genre_war                0
genre_western            0
revenue                  0
log_revenue              0
dtype: int64

In [79]:
movies.to_csv(
    OUTPUT_FILE,
    index=False
)

print("Final dataset saved:")
print(OUTPUT_FILE)

Final dataset saved:
../data/processed/final_dataset.csv

In [80]:
credits = pd.read_csv("../data/raw/credits.csv")
print("Credits shape: ", credits.shape)
credits.head()

Credits shape:  (45476, 3)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [81]:
print(credits.columns)

Index(['cast', 'crew', 'id'], dtype='str')

In [82]:
print(credits.iloc[0]["cast"])

[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]

In [83]:
print(credits.iloc[0]["crew"])

[{'credit_id': '52fe4284c3a36847f8024f49', 'department': 'Directing', 'gender': 2, 'id': 7879, 'job': 'Director', 'name': 'John Lasseter', 'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'}, {'credit_id': '52fe4284c3a36847f8024f4f', 'department': 'Writing', 'gender': 2, 'id': 12891, 'job': 'Screenplay', 'name': 'Joss Whedon', 'profile_path': '/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg'}, {'credit_id': '52fe4284c3a36847f8024f55', 'department': 'Writing', 'gender': 2, 'id': 7, 'job': 'Screenplay', 'name': 'Andrew Stanton', 'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'}, {'credit_id': '52fe4284c3a36847f8024f5b', 'department': 'Writing', 'gender': 2, 'id': 12892, 'job': 'Screenplay', 'name': 'Joel Cohen', 'profile_path': '/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg'}, {'credit_id': '52fe4284c3a36847f8024f61', 'department': 'Writing', 'gender': 0, 'id': 12893, 'job': 'Screenplay', 'name': 'Alec Sokolow', 'profile_path': '/v79vlRYi94BZUQnkkyznbGUZLjT.jpg'}, {'credit_id': '52fe4284c3a36847f8024f67', 'department': 'Production', 'gender': 1, 'id': 12894, 'job': 'Producer', 'name': 'Bonnie Arnold', 'profile_path': None}, {'credit_id': '52fe4284c3a36847f8024f6d', 'department': 'Production', 'gender': 0, 'id': 12895, 'job': 'Executive Producer', 'name': 'Ed Catmull', 'profile_path': None}, {'credit_id': '52fe4284c3a36847f8024f73', 'department': 'Production', 'gender': 2, 'id': 12896, 'job': 'Producer', 'name': 'Ralph Guggenheim', 'profile_path': None}, {'credit_id': '52fe4284c3a36847f8024f79', 'department': 'Production', 'gender': 2, 'id': 12897, 'job': 'Executive Producer', 'name': 'Steve Jobs', 'profile_path': '/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg'}, {'credit_id': '52fe4284c3a36847f8024f8b', 'department': 'Editing', 'gender': 2, 'id': 8, 'job': 'Editor', 'name': 'Lee Unkrich', 'profile_path': '/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg'}, {'credit_id': '52fe4284c3a36847f8024f91', 'department': 'Art', 'gender': 2, 'id': 7883, 'job': 'Art Direction', 'name': 'Ralph Eggleston', 'profile_path': '/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg'}, {'credit_id': '598331bf925141421201044b', 'department': 'Editing', 'gender': 2, 'id': 1168870, 'job': 'Editor', 'name': 'Robert Gordon', 'profile_path': None}, {'credit_id': '5892168cc3a36809660095f9', 'department': 'Sound', 'gender': 0, 'id': 1552883, 'job': 'Foley Editor', 'name': 'Mary Helen Leasman', 'profile_path': None}, {'credit_id': '5531824d9251415289000945', 'department': 'Visual Effects', 'gender': 0, 'id': 1453514, 'job': 'Animation', 'name': 'Kim Blanchette', 'profile_path': None}, {'credit_id': '589215969251412dcb009bf6', 'department': 'Sound', 'gender': 0, 'id': 1414182, 'job': 'ADR Editor', 'name': 'Marilyn McCoppen', 'profile_path': None}, {'credit_id': '589217099251412dc500a018', 'department': 'Sound', 'gender': 2, 'id': 7885, 'job': 'Orchestrator', 'name': 'Randy Newman', 'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'}, {'credit_id': '5693e6b29251417b0e0000e3', 'department': 'Editing', 'gender': 0, 'id': 1429549, 'job': 'Color Timer', 'name': 'Dale E. Grahn', 'profile_path': None}, {'credit_id': '572e2522c3a36869e6001a9c', 'department': 'Visual Effects', 'gender': 0, 'id': 7949, 'job': 'CG Painter', 'name': 'Robin Cooper', 'profile_path': None}, {'credit_id': '574f12309251415ca1000012', 'department': 'Writing', 'gender': 2, 'id': 7879, 'job': 'Original Story', 'name': 'John Lasseter', 'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'}, {'credit_id': '574f1240c3a3682e7300001c', 'department': 'Writing', 'gender': 2, 'id': 12890, 'job': 'Original Story', 'name': 'Pete Docter', 'profile_path': '/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg'}, {'credit_id': '574f12519251415c92000015', 'department': 'Writing', 'gender': 0, 'id': 7911, 'job': 'Original Story', 'name': 'Joe Ranft', 'profile_path': '/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg'}, {'credit_id': '574f12cec3a3682e82000022', 'department': 'Crew', 'gender': 0, 'id': 1629419, 'job': 'Post Production Supervisor', 'name': 'Patsy Bouge', 'profile_path': None}, {'credit_id': '574f14f19251415ca1000082', 'department': 'Art', 'gender': 0, 'id': 7961, 'job': 'Sculptor', 'name': 'Norm DeCarlo', 'profile_path': None}, {'credit_id': '5751ae4bc3a3683772002b7f', 'department': 'Visual Effects', 'gender': 2, 'id': 12905, 'job': 'Animation Director', 'name': 'Ash Brannon', 'profile_path': '/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg'}, {'credit_id': '5891edbe9251412dc5007cd6', 'department': 'Sound', 'gender': 2, 'id': 7885, 'job': 'Music', 'name': 'Randy Newman', 'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'}, {'credit_id': '589213d39251412dc8009832', 'department': 'Directing', 'gender': 0, 'id': 1748707, 'job': 'Layout', 'name': 'Roman Figun', 'profile_path': None}, {'credit_id': '5892173dc3a3680968009351', 'department': 'Sound', 'gender': 2, 'id': 4949, 'job': 'Orchestrator', 'name': 'Don Davis', 'profile_path': None}, {'credit_id': '589217cec3a3686b0a0052ba', 'department': 'Sound', 'gender': 0, 'id': 1372885, 'job': 'Music Editor', 'name': 'James Flamberg', 'profile_path': None}, {'credit_id': '58921831c3a3686348004a64', 'department': 'Editing', 'gender': 0, 'id': 1739962, 'job': 'Negative Cutter', 'name': 'Mary Beth Smith', 'profile_path': None}, {'credit_id': '58921838c3a36809700096c0', 'department': 'Editing', 'gender': 0, 'id': 1748513, 'job': 'Negative Cutter', 'name': 'Rick Mackay', 'profile_path': None}, {'credit_id': '589218429251412dd1009d1b', 'department': 'Art', 'gender': 0, 'id': 1458006, 'job': 'Title Designer', 'name': 'Susan Bradley', 'profile_path': None}, {'credit_id': '5891ed99c3a3680966007670', 'department': 'Crew', 'gender': 0, 'id': 1748557, 'job': 'Supervising Technical Director', 'name': 'William Reeves', 'profile_path': None}, {'credit_id': '5891edcec3a3686b0a002eb2', 'department': 'Sound', 'gender': 2, 'id': 7885, 'job': 'Songs', 'name': 'Randy Newman', 'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'}, {'credit_id': '5891edf9c3a36809700075e6', 'department': 'Writing', 'gender': 2, 'id': 7, 'job': 'Original Story', 'name': 'Andrew Stanton', 'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'}, {'credit_id': '58920f0b9251412dd7009104', 'department': 'Crew', 'gender': 2, 'id': 12890, 'job': 'Supervising Animator', 'name': 'Pete Docter', 'profile_path': '/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg'}, {'credit_id': '58920f1fc3a3680977009021', 'department': 'Sound', 'gender': 2, 'id': 2216, 'job': 'Sound Designer', 'name': 'Gary Rydstrom', 'profile_path': '/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg'}, {'credit_id': '58920f389251412dd700912d', 'department': 'Production', 'gender': 0, 'id': 12909, 'job': 'Production Supervisor', 'name': 'Karen Robert Jackson', 'profile_path': None}, {'credit_id': '58920fbd9251412dcb00969c', 'department': 'Crew', 'gender': 0, 'id': 953331, 'job': 'Executive Music Producer', 'name': 'Chris Montan', 'profile_path': None}, {'credit_id': '589210069251412dd7009219', 'department': 'Visual Effects', 'gender': 0, 'id': 7893, 'job': 'Animation Director', 'name': 'Rich Quade', 'profile_path': None}, {'credit_id': '589210329251412dcd00943b', 'department': 'Visual Effects', 'gender': 0, 'id': 8025, 'job': 'Animation', 'name': 'Michael Berenstein', 'profile_path': None}, {'credit_id': '5892103bc3a368096a009180', 'department': 'Visual Effects', 'gender': 0, 'id': 78009, 'job': 'Animation', 'name': 'Colin Brady', 'profile_path': None}, {'credit_id': '5892105dc3a3680968008db2', 'department': 'Visual Effects', 'gender': 0, 'id': 1748682, 'job': 'Animation', 'name': 'Davey Crockett Feiten', 'profile_path': None}, {'credit_id': '589210669251412dcd009466', 'department': 'Visual Effects', 'gender': 0, 'id': 1454030, 'job': 'Animation', 'name': 'Angie Glocka', 'profile_path': None}, {'credit_id': '5892107c9251412dd1009613', 'department': 'Visual Effects', 'gender': 0, 'id': 1748683, 'job': 'Animation', 'name': 'Rex Grignon', 'profile_path': None}, {'credit_id': '5892108ac3a3680973008d3f', 'department': 'Visual Effects', 'gender': 0, 'id': 1748684, 'job': 'Animation', 'name': 'Tom K. Gurney', 'profile_path': None}, {'credit_id': '58921093c3a3686348004477', 'department': 'Visual Effects', 'gender': 2, 'id': 8029, 'job': 'Animation', 'name': 'Jimmy Hayward', 'profile_path': '/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg'}, {'credit_id': '5892109b9251412dcd0094b0', 'department': 'Visual Effects', 'gender': 0, 'id': 1426773, 'job': 'Animation', 'name': 'Hal T. Hickel', 'profile_path': None}, {'credit_id': '589210a29251412dc5009a29', 'department': 'Visual Effects', 'gender': 0, 'id': 8035, 'job': 'Animation', 'name': 'Karen Kiser', 'profile_path': None}, {'credit_id': '589210ccc3a3680977009191', 'department': 'Visual Effects', 'gender': 0, 'id': 1748688, 'job': 'Animation', 'name': 'Anthony B. LaMolinara', 'profile_path': None}, {'credit_id': '589210d7c3a3686b0a004c1f', 'department': 'Visual Effects', 'gender': 0, 'id': 587314, 'job': 'Animation', 'name': 'Guionne Leroy', 'profile_path': None}, {'credit_id': '589210e1c3a36809770091a7', 'department': 'Visual Effects', 'gender': 2, 'id': 7918, 'job': 'Animation', 'name': 'Bud Luckey', 'profile_path': '/pcCh7G19FKMNijmPQg1PMH1btic.jpg'}, {'credit_id': '589210ee9251412dc200978a', 'department': 'Visual Effects', 'gender': 0, 'id': 1748689, 'job': 'Animation', 'name': 'Les Major', 'profile_path': None}, {'credit_id': '589210fa9251412dc8009595', 'department': 'Visual Effects', 'gender': 2, 'id': 7892, 'job': 'Animation', 'name': 'Glenn McQueen', 'profile_path': None}, {'credit_id': '589211029251412dc8009598', 'department': 'Visual Effects', 'gender': 0, 'id': 555795, 'job': 'Animation', 'name': 'Mark Oftedal', 'profile_path': None}, {'credit_id': '5892110b9251412dc800959d', 'department': 'Visual Effects', 'gender': 2, 'id': 7882, 'job': 'Animation', 'name': 'Jeff Pidgeon', 'profile_path': '/yLddkg5HcgbJg00cS13GVBnP0HY.jpg'}, {'credit_id': '58921113c3a36863480044e4', 'department': 'Visual Effects', 'gender': 0, 'id': 8017, 'job': 'Animation', 'name': 'Jeff Pratt', 'profile_path': None}, {'credit_id': '5892111c9251412dcb0097e9', 'department': 'Visual Effects', 'gender': 0, 'id': 1184140, 'job': 'Animation', 'name': 'Steve Rabatich', 'profile_path': None}, {'credit_id': '58921123c3a36809700090f6', 'department': 'Visual Effects', 'gender': 0, 'id': 8049, 'job': 'Animation', 'name': 'Roger Rose', 'profile_path': None}, {'credit_id': '5892112b9251412dcb0097fb', 'department': 'Visual Effects', 'gender': 0, 'id': 1509559, 'job': 'Animation', 'name': 'Steve Segal', 'profile_path': None}, {'credit_id': '589211349251412dc80095c3', 'department': 'Visual Effects', 'gender': 0, 'id': 1748691, 'job': 'Animation', 'name': 'Doug Sheppeck', 'profile_path': None}, {'credit_id': '5892113cc3a3680970009106', 'department': 'Visual Effects', 'gender': 0, 'id': 8050, 'job': 'Animation', 'name': 'Alan Sperling', 'profile_path': None}, {'credit_id': '58921148c3a3686b0a004c99', 'department': 'Visual Effects', 'gender': 0, 'id': 8010, 'job': 'Animation', 'name': 'Doug Sweetland', 'profile_path': None}, {'credit_id': '58921150c3a3680966009125', 'department': 'Visual Effects', 'gender': 0, 'id': 8044, 'job': 'Animation', 'name': 'David Tart', 'profile_path': None}, {'credit_id': '589211629251412dc5009b00', 'department': 'Visual Effects', 'gender': 0, 'id': 1454034, 'job': 'Animation', 'name': 'Ken Willard', 'profile_path': None}, {'credit_id': '589211c1c3a3686b0a004d28', 'department': 'Visual Effects', 'gender': 0, 'id': 7887, 'job': 'Visual Effects Supervisor', 'name': 'Thomas Porter', 'profile_path': None}, {'credit_id': '589211d4c3a3680968008ed9', 'department': 'Visual Effects', 'gender': 0, 'id': 1406878, 'job': 'Visual Effects', 'name': 'Mark Thomas Henne', 'profile_path': None}, {'credit_id': '589211f59251412dd4008e65', 'department': 'Visual Effects', 'gender': 0, 'id': 1748698, 'job': 'Visual Effects', 'name': 'Oren Jacob', 'profile_path': None}, {'credit_id': '58921242c3a368096a00939b', 'department': 'Visual Effects', 'gender': 0, 'id': 1748699, 'job': 'Visual Effects', 'name': 'Darwyn Peachey', 'profile_path': None}, {'credit_id': '5892124b9251412dc5009bd2', 'department': 'Visual Effects', 'gender': 0, 'id': 1748701, 'job': 'Visual Effects', 'name': 'Mitch Prater', 'profile_path': None}, {'credit_id': '58921264c3a3686b0a004dbf', 'department': 'Visual Effects', 'gender': 0, 'id': 1748703, 'job': 'Visual Effects', 'name': 'Brian M. Rosen', 'profile_path': None}, {'credit_id': '589212709251412dcd009676', 'department': 'Lighting', 'gender': 1, 'id': 12912, 'job': 'Lighting Supervisor', 'name': 'Sharon Calahan', 'profile_path': None}, {'credit_id': '5892127fc3a3686b0a004de5', 'department': 'Lighting', 'gender': 0, 'id': 7899, 'job': 'Lighting Supervisor', 'name': 'Galyn Susman', 'profile_path': None}, {'credit_id': '589212cdc3a3680970009268', 'department': 'Visual Effects', 'gender': 0, 'id': 12915, 'job': 'CG Painter', 'name': 'William Cone', 'profile_path': None}, {'credit_id': '5892130f9251412dc8009791', 'department': 'Art', 'gender': 0, 'id': 1748705, 'job': 'Sculptor', 'name': 'Shelley Daniels Lekven', 'profile_path': None}, {'credit_id': '5892131c9251412dd4008f4c', 'department': 'Visual Effects', 'gender': 2, 'id': 7889, 'job': 'Character Designer', 'name': 'Bob Pauley', 'profile_path': None}, {'credit_id': '589213249251412dd100987b', 'department': 'Visual Effects', 'gender': 2, 'id': 7918, 'job': 'Character Designer', 'name': 'Bud Luckey', 'profile_path': '/pcCh7G19FKMNijmPQg1PMH1btic.jpg'}, {'credit_id': '5892132b9251412dc80097b1', 'department': 'Visual Effects', 'gender': 2, 'id': 7, 'job': 'Character Designer', 'name': 'Andrew Stanton', 'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'}, {'credit_id': '58921332c3a368634800467b', 'department': 'Visual Effects', 'gender': 0, 'id': 12915, 'job': 'Character Designer', 'name': 'William Cone', 'profile_path': None}, {'credit_id': '5892135f9251412dd4008f90', 'department': 'Visual Effects', 'gender': 0, 'id': 1748706, 'job': 'Character Designer', 'name': 'Steve Johnson', 'profile_path': None}, {'credit_id': '58921384c3a3680973008fd4', 'department': 'Visual Effects', 'gender': 0, 'id': 1176752, 'job': 'Character Designer', 'name': 'Dan Haskett', 'profile_path': None}, {'credit_id': '5892138e9251412dc20099fc', 'department': 'Visual Effects', 'gender': 0, 'id': 1088034, 'job': 'Character Designer', 'name': 'Tom Holloway', 'profile_path': '/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg'}, {'credit_id': '58921395c3a368097700942f', 'department': 'Visual Effects', 'gender': 0, 'id': 1447465, 'job': 'Character Designer', 'name': 'Jean Gillmore', 'profile_path': None}, {'credit_id': '589213e2c3a3680973009026', 'department': 'Directing', 'gender': 0, 'id': 1748709, 'job': 'Layout', 'name': 'Desirée Mourad', 'profile_path': None}, {'credit_id': '589214099251412dc5009d57', 'department': 'Art', 'gender': 0, 'id': 1748710, 'job': 'Set Dresser', 'name': "Kelly O'Connell", 'profile_path': None}, {'credit_id': '58921411c3a3686b0a004f70', 'department': 'Art', 'gender': 0, 'id': 1443471, 'job': 'Set Dresser', 'name': 'Sonoko Konishi', 'profile_path': None}, {'credit_id': '58921434c3a368096a00956e', 'department': 'Art', 'gender': 0, 'id': 1748711, 'job': 'Set Dresser', 'name': 'Ann M. Rockwell', 'profile_path': None}, {'credit_id': '5892144ac3a36809680090de', 'department': 'Editing', 'gender': 0, 'id': 1748712, 'job': 'Editorial Manager', 'name': 'Julie M. McDonald', 'profile_path': None}, {'credit_id': '58921479c3a368096800910f', 'department': 'Editing', 'gender': 0, 'id': 1589729, 'job': 'Assistant Editor', 'name': 'Robin Lee', 'profile_path': None}, {'credit_id': '5892148b9251412dd10099cc', 'department': 'Editing', 'gender': 0, 'id': 1748716, 'job': 'Assistant Editor', 'name': 'Tom Freeman', 'profile_path': None}, {'credit_id': '589214959251412dcb009b1f', 'department': 'Editing', 'gender': 0, 'id': 1748717, 'job': 'Assistant Editor', 'name': 'Ada Cochavi', 'profile_path': None}, {'credit_id': '5892149ec3a3686348004798', 'department': 'Editing', 'gender': 0, 'id': 1336438, 'job': 'Assistant Editor', 'name': 'Dana Mulligan', 'profile_path': None}, {'credit_id': '589214adc3a368096a0095db', 'department': 'Editing', 'gender': 0, 'id': 1748718, 'job': 'Editorial Coordinator', 'name': 'Deirdre Morrison', 'profile_path': None}, {'credit_id': '589214c7c3a368097700952b', 'department': 'Production', 'gender': 0, 'id': 1748719, 'job': 'Production Coordinator', 'name': 'Lori Lombardo', 'profile_path': None}, {'credit_id': '589214cec3a368096a009603', 'department': 'Production', 'gender': 0, 'id': 1748720, 'job': 'Production Coordinator', 'name': 'Ellen Devine', 'profile_path': None}, {'credit_id': '589214e39251412dc8009904', 'department': 'Crew', 'gender': 0, 'id': 1468014, 'job': 'Unit Publicist', 'name': 'Lauren Beth Strogoff', 'profile_path': None}, {'credit_id': '58921544c3a3686b0a00507d', 'department': 'Sound', 'gender': 2, 'id': 2216, 'job': 'Sound Re-Recording Mixer', 'name': 'Gary Rydstrom', 'profile_path': '/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg'}, {'credit_id': '5892154c9251412dd1009a56', 'department': 'Sound', 'gender': 0, 'id': 1425978, 'job': 'Sound Re-Recording Mixer', 'name': 'Gary Summers', 'profile_path': None}, {'credit_id': '58921555c3a36809680091bd', 'department': 'Sound', 'gender': 2, 'id': 8276, 'job': 'Supervising Sound Editor', 'name': 'Tim Holland', 'profile_path': None}, {'credit_id': '589215c39251412dcb009c12', 'department': 'Sound', 'gender': 0, 'id': 7069, 'job': 'Sound Effects Editor', 'name': 'Pat Jackson', 'profile_path': None}, {'credit_id': '58921698c3a368096a009788', 'department': 'Crew', 'gender': 2, 'id': 15894, 'job': 'Sound Design Assistant', 'name': 'Tom Myers', 'profile_path': None}, {'credit_id': '589216a89251412dc2009ca4', 'department': 'Sound', 'gender': 0, 'id': 1414177, 'job': 'Assistant Sound Editor', 'name': 'J.R. Grubbs', 'profile_path': None}, {'credit_id': '589216c19251412dc2009cb9', 'department': 'Sound', 'gender': 1, 'id': 1748724, 'job': 'Assistant Sound Editor', 'name': 'Susan Sanford', 'profile_path': None}, {'credit_id': '589216ccc3a3680973009274', 'department': 'Sound', 'gender': 0, 'id': 1748725, 'job': 'Assistant Sound Editor', 'name': 'Susan Popovic', 'profile_path': None}, {'credit_id': '589216d79251412dc8009aa0', 'department': 'Sound', 'gender': 0, 'id': 8067, 'job': 'Assistant Sound Editor', 'name': 'Dan Engstrom', 'profile_path': None}, {'credit_id': '589216e49251412dcd009a4f', 'department': 'Production', 'gender': 1, 'id': 7902, 'job': 'Casting Consultant', 'name': 'Ruth Lambert', 'profile_path': None}, {'credit_id': '589216f39251412dc2009cf3', 'department': 'Production', 'gender': 0, 'id': 84493, 'job': 'ADR Voice Casting', 'name': 'Mickie McGowan', 'profile_path': '/k7TjJBfINsg8vLQxJwos6XObAD6.jpg'}]

In [84]:
def get_director(crew):
    try:
        crew = ast.literal_eval(crew)

        for person in crew:
            if person.get("job") == "Director":
                return person.get("name")

    except:
        pass

    return "Unknown"

In [85]:
credits["director"] = credits["crew"].apply(
    get_director
)

In [86]:
credits[
    ["id", "director"]
].head(10)

      id         director
0    862    John Lasseter
1   8844     Joe Johnston
2  15602    Howard Deutch
3  31357  Forest Whitaker
4  11862    Charles Shyer
5    949     Michael Mann
6  11860   Sydney Pollack
7  45325     Peter Hewitt
8   9091      Peter Hyams
9    710  Martin Campbell

In [87]:
def get_main_cast(cast):

    try:
        cast = ast.literal_eval(cast)

        names = []

        for person in cast[:5]:
            if "name" in person:
                names.append(person["name"])

        return names

    except:
        return []

In [88]:
credits["main_cast"] = credits["cast"].apply(
    get_main_cast
)

In [89]:
credits[
    ["id", "main_cast"]
].head(10)

      id                                          main_cast
0    862  [Tom Hanks, Tim Allen, Don Rickles, Jim Varney...
1   8844  [Robin Williams, Jonathan Hyde, Kirsten Dunst,...
2  15602  [Walter Matthau, Jack Lemmon, Ann-Margret, Sop...
3  31357  [Whitney Houston, Angela Bassett, Loretta Devi...
4  11862  [Steve Martin, Diane Keaton, Martin Short, Kim...
5    949  [Al Pacino, Robert De Niro, Val Kilmer, Jon Vo...
6  11860  [Harrison Ford, Julia Ormond, Greg Kinnear, An...
7  45325  [Jonathan Taylor Thomas, Brad Renfro, Rachael ...
8   9091  [Jean-Claude Van Damme, Powers Boothe, Dorian ...
9    710  [Pierce Brosnan, Sean Bean, Izabella Scorupco,...

In [90]:
print(credits.shape)

(45476, 5)

In [91]:
print(credits[["id", "director", "main_cast"]].head())

      id         director                                          main_cast
0    862    John Lasseter  [Tom Hanks, Tim Allen, Don Rickles, Jim Varney...
1   8844     Joe Johnston  [Robin Williams, Jonathan Hyde, Kirsten Dunst,...
2  15602    Howard Deutch  [Walter Matthau, Jack Lemmon, Ann-Margret, Sop...
3  31357  Forest Whitaker  [Whitney Houston, Angela Bassett, Loretta Devi...
4  11862    Charles Shyer  [Steve Martin, Diane Keaton, Martin Short, Kim...

In [92]:
def get_production_companies(companies):

    try:
        companies = ast.literal_eval(companies)

        names = []

        for company in companies[:5]:
            if "name" in company:
                names.append(company["name"])

        return names

    except:
        return []

In [93]:
movies = pd.read_csv(
    "../data/processed/cleaned_movies.csv"
)

print(movies.shape)
print(movies.columns)

(5363, 15)
Index(['id', 'title', 'budget', 'revenue', 'runtime', 'popularity',
       'vote_average', 'vote_count', 'original_language', 'genres',
       'production_countries', 'spoken_languages', 'release_date',
       'release_year', 'release_month'],
      dtype='str')

In [94]:
raw_movies = pd.read_csv(
    "../data/raw/movies_metadata.csv",
    low_memory=False
)

print(raw_movies.columns.tolist())

['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count']

In [95]:
raw_movies["production_companies_clean"] = raw_movies[
    "production_companies"
].apply(get_production_companies)

In [96]:
print(raw_movies[
    ["id", "production_companies_clean"]
].head())

      id                         production_companies_clean
0    862                          [Pixar Animation Studios]
1   8844  [TriStar Pictures, Teitler Film, Interscope Co...
2  15602                     [Warner Bros., Lancaster Gate]
3  31357           [Twentieth Century Fox Film Corporation]
4  11862       [Sandollar Productions, Touchstone Pictures]

In [97]:
credits_clean = credits[
    ["id", "director", "main_cast"]
].copy()

In [98]:
companies_clean = raw_movies[
    ["id", "production_companies_clean"]
].copy()

In [99]:
credits_clean["id"] = pd.to_numeric(
    credits_clean["id"],
    errors="coerce"
)

companies_clean["id"] = pd.to_numeric(
    companies_clean["id"],
    errors="coerce"
)

movies["id"] = pd.to_numeric(
    movies["id"],
    errors="coerce"
)

In [100]:
movies = movies.merge(
    credits_clean,
    on="id",
    how="left"
)

In [101]:
movies = movies.merge(
    companies_clean,
    on="id",
    how="left"
)

In [102]:
print("New shape:", movies.shape)

print(
    movies[
        [
            "id",
            "title",
            "director",
            "main_cast",
            "production_companies_clean"
        ]
    ].head()
)

New shape: (5381, 18)
      id              title         director  \
0    862          Toy Story    John Lasseter
1   8844            Jumanji     Joe Johnston
2  31357  Waiting to Exhale  Forest Whitaker
3    949               Heat     Michael Mann
4   9091       Sudden Death      Peter Hyams

                                           main_cast  \
0  [Tom Hanks, Tim Allen, Don Rickles, Jim Varney...
1  [Robin Williams, Jonathan Hyde, Kirsten Dunst,...
2  [Whitney Houston, Angela Bassett, Loretta Devi...
3  [Al Pacino, Robert De Niro, Val Kilmer, Jon Vo...
4  [Jean-Claude Van Damme, Powers Boothe, Dorian ...

                          production_companies_clean
0                          [Pixar Animation Studios]
1  [TriStar Pictures, Teitler Film, Interscope Co...
2           [Twentieth Century Fox Film Corporation]
3  [Regency Enterprises, Forward Pass, Warner Bros.]
4  [Universal Pictures, Imperial Entertainment, S...

In [103]:
print(
    movies[
        [
            "id",
            "title",
            "director",
            "main_cast",
            "production_companies_clean"
        ]
    ].head()
)

      id              title         director  \
0    862          Toy Story    John Lasseter
1   8844            Jumanji     Joe Johnston
2  31357  Waiting to Exhale  Forest Whitaker
3    949               Heat     Michael Mann
4   9091       Sudden Death      Peter Hyams

                                           main_cast  \
0  [Tom Hanks, Tim Allen, Don Rickles, Jim Varney...
1  [Robin Williams, Jonathan Hyde, Kirsten Dunst,...
2  [Whitney Houston, Angela Bassett, Loretta Devi...
3  [Al Pacino, Robert De Niro, Val Kilmer, Jon Vo...
4  [Jean-Claude Van Damme, Powers Boothe, Dorian ...

                          production_companies_clean
0                          [Pixar Animation Studios]
1  [TriStar Pictures, Teitler Film, Interscope Co...
2           [Twentieth Century Fox Film Corporation]
3  [Regency Enterprises, Forward Pass, Warner Bros.]
4  [Universal Pictures, Imperial Entertainment, S...

In [104]:
movies["cast_count"] = movies["main_cast"].apply(
    lambda x: len(x) if isinstance(x, list) else 0
)

In [105]:
movies["production_company_count"] = movies[
    "production_companies_clean"
].apply(
    lambda x: len(x) if isinstance(x, list) else 0
)

In [106]:
director_counts = movies["director"].value_counts()

movies["director_movie_count"] = movies["director"].map(
    director_counts
)

In [107]:
print(
    movies[
        [
            "title",
            "director",
            "cast_count",
            "production_company_count",
            "director_movie_count"
        ]
    ].head(10)
)

                    title         director  cast_count  \
0               Toy Story    John Lasseter           5
1                 Jumanji     Joe Johnston           5
2       Waiting to Exhale  Forest Whitaker           5
3                    Heat     Michael Mann           5
4            Sudden Death      Peter Hyams           5
5               GoldenEye  Martin Campbell           5
6  The American President       Rob Reiner           5
7                   Nixon     Oliver Stone           5
8        Cutthroat Island     Renny Harlin           5
9                  Casino  Martin Scorsese           5

   production_company_count  director_movie_count
0                         1                     5
1                         3                     7
2                         1                     1
3                         3                    10
4                         3                    10
5                         2                     8
6                         2                    13
7                         2                    17
8                         4                    16
9                         4                    18

In [108]:
print(
    movies[
        [
            "title",
            "director",
            "cast_count",
            "production_company_count",
            "director_movie_count"
        ]
    ].head(10)
)

                    title         director  cast_count  \
0               Toy Story    John Lasseter           5
1                 Jumanji     Joe Johnston           5
2       Waiting to Exhale  Forest Whitaker           5
3                    Heat     Michael Mann           5
4            Sudden Death      Peter Hyams           5
5               GoldenEye  Martin Campbell           5
6  The American President       Rob Reiner           5
7                   Nixon     Oliver Stone           5
8        Cutthroat Island     Renny Harlin           5
9                  Casino  Martin Scorsese           5

   production_company_count  director_movie_count
0                         1                     5
1                         3                     7
2                         1                     1
3                         3                    10
4                         3                    10
5                         2                     8
6                         2                    13
7                         2                    17
8                         4                    16
9                         4                    18

In [109]:
movies = movies.sort_values(
    "release_date"
).reset_index(drop=True)

movies["director_previous_movies"] = (
    movies.groupby("director").cumcount()
)

In [110]:
print(
    movies[
        [
            "title",
            "release_date",
            "director",
            "director_previous_movies"
        ]
    ].head(20)
)

                            title release_date            director  \
0           The Birth of a Nation   1915-02-08       D.W. Griffith
1                       The Cheat   1915-12-13    Cecil B. DeMille
2    20,000 Leagues Under the Sea   1916-12-24        Stuart Paton
3                          Mickey   1918-08-01    F. Richard Jones
4                         The Kid   1921-01-21     Charlie Chaplin
5                   Foolish Wives   1922-01-11  Erich von Stroheim
6             The Thief of Bagdad   1924-03-18         Raoul Walsh
7                   The Gold Rush   1925-06-25     Charlie Chaplin
8                 The Merry Widow   1925-08-26  Erich von Stroheim
9                The Unholy Three   1925-09-16        Tod Browning
10                 The Big Parade   1925-11-05          King Vidor
11  Ben-Hur: A Tale of the Christ   1925-12-30      Charles Brabin
12                       Sparrows   1926-05-14    William Beaudine
13            Flesh and the Devil   1926-12-25      Clarence Brown
14                     Metropolis   1927-01-10          Fritz Lang
15                   My Best Girl   1927-10-31          Sam Taylor
16            Across to Singapore   1928-04-07        William Nigh
17             Lights of New York   1928-07-18           Bryan Foy
18            The Mysterious Lady   1928-08-04   Harold S. Bucquet
19               West of Zanzibar   1928-11-24        Tod Browning

    director_previous_movies
0                          0
1                          0
2                          0
3                          0
4                          0
5                          0
6                          0
7                          1
8                          1
9                          0
10                         0
11                         0
12                         0
13                         0
14                         0
15                         0
16                         0
17                         0
18                         0
19                         1

In [111]:
model2_features = [
    "budget",
    "log_budget",
    "runtime",
    "release_year",
    "release_month",
    "original_language",
    "main_country",
    "cast_count",
    "production_company_count",
    "director_previous_movies"
]

In [112]:
genre_columns = [
    column
    for column in movies.columns
    if column.startswith("genre_")
]

model2_features.extend(genre_columns)

In [113]:
model2_features.append("revenue")
model2_features.append("log_revenue")

In [116]:
movies["log_budget"] = np.log1p(
    movies["budget"]
)

movies["log_revenue"] = np.log1p(
    movies["revenue"]
)

In [117]:
def get_main_country(countries):

    if isinstance(countries, list) and len(countries) > 0:
        return countries[0]

    return "Unknown"

In [118]:
movies["main_country"] = movies[
    "production_countries"
].apply(get_main_country)

In [119]:
print(
    movies[
        [
            "title",
            "budget",
            "log_budget",
            "revenue",
            "log_revenue",
            "main_country"
        ]
    ].head()
)

                          title    budget  log_budget     revenue  \
0         The Birth of a Nation  100000.0   11.512935  11000000.0
1                     The Cheat   17311.0    9.759155    137365.0
2  20,000 Leagues Under the Sea  200000.0   12.206078   8000000.0
3                        Mickey  250000.0   12.429220   8000000.0
4                       The Kid  250000.0   12.429220   2500000.0

   log_revenue main_country
0    16.213406      Unknown
1    11.830404      Unknown
2    15.894952      Unknown
3    15.894952      Unknown
4    14.731802      Unknown

In [120]:
model2_features = [
    "budget",
    "log_budget",
    "runtime",
    "release_year",
    "release_month",
    "original_language",
    "main_country",
    "cast_count",
    "production_company_count",
    "director_previous_movies"
]

In [121]:
genre_columns = [
    column
    for column in movies.columns
    if column.startswith("genre_")
]

model2_features.extend(genre_columns)

model2_features.append("revenue")
model2_features.append("log_revenue")

In [122]:
model2_data = movies[
    model2_features
].copy()

In [123]:
print("Model 2 shape:", model2_data.shape)

print("\nMissing columns:")

missing_columns = [
    column
    for column in model2_features
    if column not in movies.columns
]

print(missing_columns)

Model 2 shape: (5381, 12)

Missing columns:
[]

In [124]:
print("\nMissing values:")

print(
    model2_data.isnull()
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

Missing values:
budget                      0
log_budget                  0
runtime                     0
release_year                0
release_month               0
original_language           0
main_country                0
cast_count                  0
production_company_count    0
director_previous_movies    0
revenue                     0
log_revenue                 0
dtype: int64

In [125]:
OUTPUT_FILE = "../data/processed/model2_dataset.csv"

model2_data.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\nModel 2 dataset saved to:")
print(OUTPUT_FILE)

Model 2 dataset saved to:
../data/processed/model2_dataset.csv

In [126]:
movies["director_previous_avg_log_revenue"] = (
    movies.groupby("director")["log_revenue"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
)

In [128]:
movies["director_previous_avg_log_revenue"] = (
    movies["director_previous_avg_log_revenue"]
    .fillna(
        movies["log_revenue"].mean()
    )
)

In [129]:
print(
    movies[
        [
            "title",
            "release_date",
            "director",
            "director_previous_movies",
            "director_previous_avg_log_revenue"
        ]
    ].head(20)
)

                            title release_date            director  \
0           The Birth of a Nation   1915-02-08       D.W. Griffith
1                       The Cheat   1915-12-13    Cecil B. DeMille
2    20,000 Leagues Under the Sea   1916-12-24        Stuart Paton
3                          Mickey   1918-08-01    F. Richard Jones
4                         The Kid   1921-01-21     Charlie Chaplin
5                   Foolish Wives   1922-01-11  Erich von Stroheim
6             The Thief of Bagdad   1924-03-18         Raoul Walsh
7                   The Gold Rush   1925-06-25     Charlie Chaplin
8                 The Merry Widow   1925-08-26  Erich von Stroheim
9                The Unholy Three   1925-09-16        Tod Browning
10                 The Big Parade   1925-11-05          King Vidor
11  Ben-Hur: A Tale of the Christ   1925-12-30      Charles Brabin
12                       Sparrows   1926-05-14    William Beaudine
13            Flesh and the Devil   1926-12-25      Clarence Brown
14                     Metropolis   1927-01-10          Fritz Lang
15                   My Best Girl   1927-10-31          Sam Taylor
16            Across to Singapore   1928-04-07        William Nigh
17             Lights of New York   1928-07-18           Bryan Foy
18            The Mysterious Lady   1928-08-04   Harold S. Bucquet
19               West of Zanzibar   1928-11-24        Tod Browning

    director_previous_movies  director_previous_avg_log_revenue
0                          0                          16.741268
1                          0                          16.741268
2                          0                          16.741268
3                          0                          16.741268
4                          0                          16.741268
5                          0                          16.741268
6                          0                          16.741268
7                          1                          14.731802
8                          1                          12.899722
9                          0                          16.741268
10                         0                          16.741268
11                         0                          16.741268
12                         0                          16.741268
13                         0                          16.741268
14                         0                          16.741268
15                         0                          16.741268
16                         0                          16.741268
17                         0                          16.741268
18                         0                          16.741268
19                         1                          13.464535

In [130]:
print(
    movies[
        [
            "director",
            "director_previous_movies",
            "director_previous_avg_log_revenue"
        ]
    ].tail(20)
)

               director  director_previous_movies  \
5361      Patty Jenkins                         1
5362        David Soren                         1
5363      Alex Kurtzman                         1
5364   Johannes Roberts                         0
5365         Kyle Balda                         2
5366      Lucia Aniello                         0
5367          Brian Fee                         0
5368    Colin Trevorrow                         2
5369        Michael Bay                        12
5370      Sofia Coppola                         4
5371       Edgar Wright                         4
5372       David Lowery                         1
5373        Matt Reeves                         3
5374  Christopher Nolan                         9
5375         Luc Besson                         8
5376       David Leitch                         0
5377    Anthony Leondis                         1
5378      Nikolaj Arcel                         1
5379    Taylor Sheridan                         0
5380        Luis Prieto                         0

      director_previous_avg_log_revenue
5361                          17.916145
5362                          19.459439
5363                          16.336008
5364                          16.741268
5365                          20.269494
5366                          16.741268
5367                          16.741268
5368                          18.170730
5369                          19.640873
5370                          17.361059
5371                          17.687123
5372                          18.783206
5373                          18.779030
5374                          18.609284
5375                          17.479588
5376                          16.741268
5377                          17.216708
5378                          15.842960
5379                          16.741268
5380                          16.741268

In [131]:
model3_features = [
    "budget",
    "log_budget",
    "runtime",
    "release_year",
    "release_month",
    "original_language",
    "main_country",
    "director_previous_movies",
    "director_previous_avg_log_revenue"
]

In [132]:
genre_columns = [
    column
    for column in movies.columns
    if column.startswith("genre_")
]

model3_features.extend(genre_columns)

In [133]:
model3_features.append("revenue")
model3_features.append("log_revenue")

In [134]:
model3_data = movies[
    model3_features
].copy()

In [135]:
print("Model 3 shape:", model3_data.shape)

print("\nMissing values:")
print(
    model3_data.isnull().sum()
    .sort_values(ascending=False)
)

Model 3 shape: (5381, 11)

Missing values:
budget                               0
log_budget                           0
runtime                              0
release_year                         0
release_month                        0
original_language                    0
main_country                         0
director_previous_movies             0
director_previous_avg_log_revenue    0
revenue                              0
log_revenue                          0
dtype: int64

In [136]:
OUTPUT_FILE = "../data/processed/model3_dataset.csv"

model3_data.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\nModel 3 dataset saved to:")
print(OUTPUT_FILE)

Model 3 dataset saved to:
../data/processed/model3_dataset.csv

In [137]:
print("Model 3 shape:", model3_data.shape)

print("\nColumns:")
print(model3_data.columns.tolist())

print("\nMissing values:")
print(model3_data.isnull().sum())

Model 3 shape: (5381, 11)

Columns:
['budget', 'log_budget', 'runtime', 'release_year', 'release_month', 'original_language', 'main_country', 'director_previous_movies', 'director_previous_avg_log_revenue', 'revenue', 'log_revenue']

Missing values:
budget                               0
log_budget                           0
runtime                              0
release_year                         0
release_month                        0
original_language                    0
main_country                         0
director_previous_movies             0
director_previous_avg_log_revenue    0
revenue                              0
log_revenue                          0
dtype: int64

MODEL 1 - RE

In [138]:
print("Genre columns:")
print([
    column
    for column in movies.columns
    if column.startswith("genre_")
])

Genre columns:
[]

In [139]:
print("Number of genre columns:", len([
    column
    for column in movies.columns
    if column.startswith("genre_")
]))

Number of genre columns: 0

In [140]:
print(movies[["title", "genres"]].head())

                          title  \
0         The Birth of a Nation
1                     The Cheat
2  20,000 Leagues Under the Sea
3                        Mickey
4                       The Kid

                                              genres
0                        ['Drama', 'History', 'War']
1                                          ['Drama']
2  ['Adventure', 'Drama', 'Action', 'Science Fict...
3                                ['Comedy', 'Drama']
4                                ['Comedy', 'Drama']

In [141]:
print(type(movies["genres"].iloc[0]))

<class 'str'>

In [142]:
print(movies["genres"].iloc[0])

['Drama', 'History', 'War']

In [143]:
GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "History",
    "Horror",
    "Music",
    "Mystery",
    "Romance",
    "Science Fiction",
    "Thriller",
    "War",
    "Western"
]

In [144]:
for genre in GENRES:
    column_name = "genre_" + genre.lower().replace(" ", "_")

    movies[column_name] = movies["genres"].apply(
        lambda genres: 1 if genre in genres else 0
    )

In [145]:
genre_columns = [
    column
    for column in movies.columns
    if column.startswith("genre_")
]

print("Number of genre columns:", len(genre_columns))
print(genre_columns)

Number of genre columns: 18
['genre_action', 'genre_adventure', 'genre_animation', 'genre_comedy', 'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family', 'genre_fantasy', 'genre_history', 'genre_horror', 'genre_music', 'genre_mystery', 'genre_romance', 'genre_science_fiction', 'genre_thriller', 'genre_war', 'genre_western']

In [146]:
print(
    movies[
        ["title"] + genre_columns
    ].head()
)

                          title  genre_action  genre_adventure  \
0         The Birth of a Nation             0                0
1                     The Cheat             0                0
2  20,000 Leagues Under the Sea             1                1
3                        Mickey             0                0
4                       The Kid             0                0

   genre_animation  genre_comedy  genre_crime  genre_documentary  genre_drama  \
0                0             0            0                  0            1
1                0             0            0                  0            1
2                0             0            0                  0            1
3                0             1            0                  0            1
4                0             1            0                  0            1

   genre_family  genre_fantasy  genre_history  genre_horror  genre_music  \
0             0              0              1             0            0
1             0              0              0             0            0
2             0              0              0             0            0
3             0              0              0             0            0
4             0              0              0             0            0

   genre_mystery  genre_romance  genre_science_fiction  genre_thriller  \
0              0              0                      0               0
1              0              0                      0               0
2              0              0                      1               0
3              0              0                      0               0
4              0              0                      0               0

   genre_war  genre_western
0          1              0
1          0              0
2          0              0
3          0              0
4          0              0

MODEL 4

In [147]:
model4_features = [
    "budget",
    "log_budget",
    "runtime",
    "release_year",
    "release_month",
    "original_language",
    "main_country"
]

genre_columns = [
    column
    for column in movies.columns
    if column.startswith("genre_")
]

model4_features.extend(genre_columns)

model4_features.append("revenue")
model4_features.append("log_revenue")

In [148]:
model4_data = movies[
    model4_features
].copy()

In [149]:
print("Model 4 shape:", model4_data.shape)

print("\nNumber of genre columns:", len(genre_columns))

print("\nColumns:")
print(model4_data.columns.tolist())

Model 4 shape: (5381, 27)

Number of genre columns: 18

Columns:
['budget', 'log_budget', 'runtime', 'release_year', 'release_month', 'original_language', 'main_country', 'genre_action', 'genre_adventure', 'genre_animation', 'genre_comedy', 'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family', 'genre_fantasy', 'genre_history', 'genre_horror', 'genre_music', 'genre_mystery', 'genre_romance', 'genre_science_fiction', 'genre_thriller', 'genre_war', 'genre_western', 'revenue', 'log_revenue']

In [150]:
print("\nMissing values:")

print(
    model4_data.isnull()
    .sum()
    .sort_values(ascending=False)
)

Missing values:
budget                   0
log_budget               0
runtime                  0
release_year             0
release_month            0
original_language        0
main_country             0
genre_action             0
genre_adventure          0
genre_animation          0
genre_comedy             0
genre_crime              0
genre_documentary        0
genre_drama              0
genre_family             0
genre_fantasy            0
genre_history            0
genre_horror             0
genre_music              0
genre_mystery            0
genre_romance            0
genre_science_fiction    0
genre_thriller           0
genre_war                0
genre_western            0
revenue                  0
log_revenue              0
dtype: int64

In [151]:
OUTPUT_FILE = "../data/processed/model4_dataset.csv"

model4_data.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\nModel 4 dataset saved to:")
print(OUTPUT_FILE)

Model 4 dataset saved to:
../data/processed/model4_dataset.csv